project:
  type: manuscript
  output-dir: docs
  render:
    - "!*.md"
  post-render:
    - ./post-render

resources:
  - context.json
  - prefixes.json

repo-url: https://github.com/gbv/jskos

manuscript:
  article: jskos.qmd
  code-links:
    - repo

metadata-files:
  - version.yaml

title: JSKOS data format for Knowledge Organization Systems
authors:
  - name: Jakob Voß
    orcid: 0000-0002-7613-4123
    affiliations:
    - name: Verbundzentrale des GBV (VZG)    
# abstract: |
# ...

format:
  html:
    number-sections: true
    code-line-numbers: false
    highlight-style: kate
    theme: flatly
    css: style.css
    crossref:
      lst-prefix: "Example"
      lst-title: "Example"
